"""Spanish language pack.

Accented and unaccented surface forms are both registered, because dictated
text and typed fallback text disagree about accents far more often than they
disagree about spelling.
"""

from __future__ import annotations

from app.nlp.lexicons.base import Lexicon

_NUMBER_WORDS: dict[str, float] = {
    "cero": 0, "un": 1, "uno": 1, "una": 1,
    "dos": 2, "tres": 3, "cuatro": 4, "cinco": 5,
    "seis": 6, "siete": 7, "ocho": 8, "nueve": 9, "diez": 10,
    "once": 11, "doce": 12, "trece": 13, "catorce": 14, "quince": 15,
    "dieciseis": 16, "dieciséis": 16, "diecisiete": 17,
    "dieciocho": 18, "diecinueve": 19, "veinte": 20,
    "treinta": 30, "cuarenta": 40, "cincuenta": 50, "cien": 100,
    "medio": 0.5, "media": 0.5, "cuarto": 0.25,
    "docena": 12, "par": 2,
}

_UNITS: dict[str, str] = {
    "litro": "litre", "litros": "litre",
    "mililitro": "ml", "mililitros": "ml",
    "kilo": "kg", "kilos": "kg",
    "kilogramo": "kg", "kilogramos": "kg",
    "gramo": "g", "gramos": "g",
    "libra": "lb", "libras": "lb",
    "botella": "bottle", "botellas": "bottle",
    "paquete": "packet", "paquetes": "packet",
    "caja": "box", "cajas": "box",
    "lata": "can", "latas": "can",
    "bolsa": "bag", "bolsas": "bag",
    "docena": "dozen", "docenas": "dozen",
    "barra": "loaf", "barras": "loaf",
    "pieza": "piece", "piezas": "piece",
    "manojo": "bunch",
    "tarro": "jar", "frasco": "jar",
}

_ATTRIBUTES: dict[str, str] = {
    "orgánico": "organic", "organico": "organic",
    "orgánica": "organic", "organica": "organic",
    "orgánicos": "organic", "organicos": "organic",
    "orgánicas": "organic", "organicas": "organic",
    "fresco": "fresh", "fresca": "fresh", "frescos": "fresh",
    "frescas": "fresh",
    "congelado": "frozen", "congelada": "frozen", "congelados": "frozen",
    "entera": "whole", "entero": "whole",
    "descremada": "low-fat", "desnatada": "low-fat",
    "semidescremada": "low-fat", "ligera": "low-fat",
    "integral": "whole-grain", "integrales": "whole-grain",
    "sin gluten": "gluten-free",
    "sin azúcar": "sugar-free", "sin azucar": "sugar-free",
    "sin sal": "unsalted",
    "griego": "greek", "griega": "greek",
    "moreno": "brown", "morena": "brown",
    "blanco": "white", "blanca": "white",
    "negro": "dark", "oscuro": "dark",
    "vegano": "vegan", "vegana": "vegan",
    "natural": "fresh",
}

_ITEM_ALIASES: dict[str, str] = {
    # Everyday grocery vocabulary, mapped to the catalog's English terms.
    "leche": "milk", "leche de almendras": "almond milk",
    "leche de soja": "soy milk", "leche de avena": "oat milk",
    "yogur": "yogurt", "yogurt": "yogurt", "queso": "cheese",
    "mantequilla": "butter", "huevo": "eggs", "huevos": "eggs",
    "nata": "cream", "crema": "cream",
    "pan": "bread", "barra de pan": "bread", "bagel": "bagels",
    "tortillas": "tortillas", "arroz": "rice", "harina": "flour",
    "azúcar": "sugar", "azucar": "sugar", "sal": "salt",
    "aceite": "oil", "aceite de oliva": "olive oil",
    "té": "tea", "te": "tea", "café": "coffee", "cafe": "coffee",
    "agua": "water", "zumo": "juice", "jugo": "juice", "refresco": "cola",
    "manzana": "apple", "manzanas": "apple", "plátano": "banana",
    "platano": "banana", "plátanos": "banana", "platanos": "banana",
    "naranja": "orange", "naranjas": "orange", "mango": "mango",
    "uvas": "grapes", "limón": "lemon", "limon": "lemon", "lima": "lime",
    "fresa": "strawberries", "fresas": "strawberries",
    "arándanos": "blueberries", "arandanos": "blueberries",
    "sandía": "watermelon", "sandia": "watermelon", "pera": "pear",
    "tomate": "tomatoes", "tomates": "tomatoes", "patata": "potatoes",
    "patatas": "potatoes", "papa": "potatoes", "papas": "potatoes",
    "cebolla": "onions", "cebollas": "onions", "ajo": "garlic",
    "zanahoria": "carrots", "zanahorias": "carrots",
    "espinaca": "spinach", "espinacas": "spinach",
    "pepino": "cucumber", "lechuga": "lettuce", "aguacate": "avocado",
    "calabaza": "pumpkin", "guisantes": "peas", "lentejas": "lentils",
    "garbanzos": "chickpeas", "frijoles": "beans",
    "pollo": "chicken", "carne": "beef", "ternera": "beef",
    "cerdo": "pork", "pavo": "turkey", "pescado": "fish",
    "salmón": "salmon", "salmon": "salmon", "atún": "tuna", "atun": "tuna",
    "tocino": "bacon", "salchichas": "sausages",
    "pasta": "pasta", "espaguetis": "spaghetti", "cereal": "cereal",
    "avena": "oats", "miel": "honey", "mermelada": "jam",
    "chocolate": "chocolate", "galletas": "crackers",
    "patatas fritas": "chips", "helado": "ice cream",
    "palomitas": "popcorn", "salsa": "salsa",
    "pasta de dientes": "toothpaste", "dentífrico": "toothpaste",
    "dentifrico": "toothpaste", "cepillo de dientes": "toothbrush",
    "champú": "shampoo", "champu": "shampoo", "jabón": "soap",
    "jabon": "soap", "acondicionador": "conditioner",
    "detergente": "detergent", "suavizante": "fabric softener",
    "papel higiénico": "toilet paper", "papel higienico": "toilet paper",
    "servilletas": "paper towels", "pañales": "diapers",
    "panales": "diapers", "toallitas": "baby wipes",
}

_STOPWORDS: frozenset[str] = frozenset({
    "el", "la", "los", "las", "un", "una", "unos", "unas",
    "de", "del", "al", "a", "en", "por", "para", "con", "y", "o",
    "mi", "mis", "me", "yo", "nos", "nuestra", "nuestro",
    "lista", "listas", "carrito", "cesta", "compra", "compras",
    "por favor", "favor", "porfavor",
    "que", "es", "son", "esta", "este", "eso", "esto",
    "algo", "algunos", "algunas", "más", "mas", "también", "tambien",
})

SPANISH = Lexicon(
    code="es",
    label="Español (Spanish)",
    locales=("es-ES", "es-MX", "es-AR", "es-CO", "es-US"),
    default_locale="es-ES",
    add_cues=(
        r"quiero\s+comprar",
        r"me\s+gustar[íi]a\s+comprar",
        r"tengo\s+que\s+comprar",
        r"necesito\s+comprar",
        r"a[ñn][áa]d(?:e|a|ir)",
        r"agrega(?:r|me)?",
        r"a[ñn]ade",
        r"pon(?:er|me|le)?",
        r"mete",
        r"compra(?:r|me)?",
        r"necesito",
        r"quiero",
        r"incluye",
        r"apunta",
        r"a[ñn]ada",
    ),
    remove_cues=(
        r"quita(?:r|me)?",
        r"elimina(?:r)?",
        r"borra(?:r)?",
        r"saca(?:r)?",
        r"remueve",
        r"ya\s+no\s+necesito",
        r"deshazte\s+de",
    ),
    update_cues=(
        r"cambia(?:r)?",
        r"actualiza(?:r)?",
        r"modifica(?:r)?",
        r"reemplaza(?:r)?",
        r"sustituye",
        r"haz\s+que\s+sea",
        r"pon\s+mejor",
    ),
    complete_cues=(
        r"ya\s+(?:compr[ée]|tengo|consegu[íi])",
        r"marca(?:r)?\s+como\s+(?:hecho|comprado)",
        r"listo\s+con",
    ),
    search_cues=(
        r"busca(?:r|me)?",
        r"encuentra(?:me)?",
        r"mu[ée]stra(?:me)?",
        r"ens[ée][ñn]a(?:me)?",
        r"tienes",
        r"hay",
        r"cu[áa]nto\s+cuesta",
        r"qu[ée]\s+precio\s+tiene",
    ),
    show_cues=(
        r"(?:mu[ée]stra|ens[ée][ñn]a|lee)(?:me)?\s+(?:mi\s+)?"
        r"(?:lista|carrito|cesta)(?:\s+de\s+compras?)?",
        r"qu[ée]\s+hay\s+en\s+(?:mi\s+)?lista",
        r"qu[ée]\s+necesito",
        r"^mi\s+lista(?:\s+de\s+compras?)?$",
    ),
    clear_cues=(
        r"(?:vac[íi]a|limpia|borra|elimina)\s+(?:toda\s+)?(?:mi|la)\s+"
        r"(?:lista|carrito|cesta)",
        r"borra\s+todo",
        r"elimina\s+todo",
        r"empezar?\s+de\s+nuevo",
        r"limpiar?\s+todo",
    ),
    confirm_words=frozenset({
        "confirmar", "confirma", "sí", "si", "claro", "vale",
        "adelante", "correcto", "hazlo", "ok",
    }),
    cancel_words=frozenset({
        "cancelar", "cancela", "no", "para", "detente",
        "olvídalo", "olvidalo", "nada",
    }),
    number_words=_NUMBER_WORDS,
    tens_words={"veinte": 20, "treinta": 30, "cuarenta": 40, "cincuenta": 50},
    half_cues=("y medio", "y media"),
    units=_UNITS,
    dozen_words=frozenset({"docena", "docenas"}),
    max_price_cues=(
        r"menos\s+de", r"por\s+debajo\s+de", r"bajo",
        r"m[áa]ximo", r"hasta", r"no\s+m[áa]s\s+de",
        r"m[áa]s\s+barato\s+que", r"under",
    ),
    min_price_cues=(
        r"m[áa]s\s+de", r"por\s+encima\s+de", r"arriba\s+de",
        r"al\s+menos", r"m[íi]nimo", r"desde",
    ),
    range_cues=(r"entre",),
    range_join=("y", "a", "and"),
    currency_words=("dólares", "dolares", "dólar", "dolar", "euros",
                    "euro", "pesos", "peso"),
    attributes=_ATTRIBUTES,
    item_aliases=_ITEM_ALIASES,
    stopwords=_STOPWORDS,
    replacement_cues=(r"por", r"a", r"con", r"en\s+vez\s+de"),
    examples=(
        "Necesito dos litros de leche",
        "Añade 5 manzanas",
        "Quita la leche de mi lista",
        "Busca manzanas orgánicas",
        "Busca pasta de dientes menos de $5",
        "Muestra mi lista",
    ),
)
